version: '3.7'
services:
  python: 
    image: gamification-engine:1.0
    environment:
      - INI_FILE=gengine_quickstart_template/production.ini
      - RESET_DB=
      - UWSGI_CONF=gengine_quickstart_template/production.uwsgi
    volumes:
      - uwsgi_socket:/tmp
    build:
      args:
        - SETUP_MODE=install
  nginx:
    image: nginx:alpine
    depends_on:
      - python
    volumes:
      - ./prod-config/nginx.conf:/etc/nginx/nginx.conf
      - uwsgi_socket:/tmp
    ports:
      - 8080:80
    networks:
      - backend